import '../../data/models/preset_model.dart';
import '../../data/models/project_row_model.dart';
import '../../core/services/local_storage_service.dart';

/// Repository for managing presets
/// Handles CRUD operations with local storage
class PresetRepository {
  final LocalStorageService _storageService;

  PresetRepository(this._storageService);

  /// Get all presets
  Future<List<PresetModel>> getAllPresets() async {
    try {
      final presets = await _storageService.getPresets();
      // Always include default presets
      final allPresets = [..._getDefaultPresets(), ...presets];
      return allPresets;
    } catch (e) {
      // Return default presets if there's an error
      return _getDefaultPresets();
    }
  }

  /// Get preset by ID
  Future<PresetModel?> getPresetById(String id) async {
    final presets = await getAllPresets();
    return presets.where((preset) => preset.id == id).firstOrNull;
  }

  /// Create a new preset
  Future<PresetModel> createPreset({
    required String name,
    String? description,
    required List<ProjectRowModel> rows,
  }) async {
    final preset = PresetModel(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      name: name,
      defaultRows: rows,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    // Save only the new preset to storage
    await _storageService.savePreset(preset);

    return preset;
  }

  /// Update an existing preset
  Future<void> updatePreset(PresetModel preset) async {
    // Only update user-created presets
    if (!preset.isDefault) {
      await _storageService.savePreset(preset);
    }
  }

  /// Delete a preset
  Future<void> deletePreset(String id) async {
    // Only delete user-created presets
    await _storageService.deletePreset(id);
  }

  /// Check if preset name exists
  Future<bool> presetNameExists(String name, {String? excludeId}) async {
    final presets = await getAllPresets();
    return presets.any((preset) =>
        preset.name.toLowerCase() == name.toLowerCase() &&
        preset.id != excludeId &&
        !preset.isDefault); // Only check user-created presets
  }

  /// Save presets to storage
  Future<void> _savePresets(List<PresetModel> presets) async {
    // Clear existing presets and save only user-created presets
    await _storageService.clearPresets();
    for (final preset in presets.where((p) => !p.isDefault)) {
      await _storageService.savePreset(preset);
    }
  }

  /// Get default presets
  List<PresetModel> _getDefaultPresets() {
    return [
      PresetModel(
        id: 'default_solar_5kw',
        name: '5kW Solar System',
        defaultRows: [
          const ProjectRowModel(
            id: '1',
            title: 'Solar Panels (400W)',
            quantity: 15,
            unit: 'pcs',
            description: 'Solar Panels (400W)',
            estimatedPrice: 8500.0,
            isAutoGenerated: true,
            category: 'solar_panels',
          ),
          const ProjectRowModel(
            id: '2',
            title: '5kW Inverter',
            quantity: 1,
            unit: 'unit',
            description: '5kW Inverter',
            estimatedPrice: 45000.0,
            isAutoGenerated: true,
            category: 'inverter',
          ),
          const ProjectRowModel(
            id: '3',
            title: 'Installation & Mounting',
            quantity: 1,
            unit: 'lot',
            description: 'Installation & Mounting',
            estimatedPrice: 25000.0,
            isAutoGenerated: true,
            category: 'installation',
          ),
        ],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        isDefault: true,
      ),
      PresetModel(
        id: 'default_solar_10kw',
        name: '10kW Solar System',
        defaultRows: [
          const ProjectRowModel(
            id: '1',
            title: 'Solar Panels (400W)',
            quantity: 30,
            unit: 'pcs',
            description: 'Solar Panels (400W)',
            estimatedPrice: 8500.0,
            isAutoGenerated: true,
            category: 'solar_panels',
          ),
          const ProjectRowModel(
            id: '2',
            title: '10kW Inverter',
            quantity: 1,
            unit: 'unit',
            description: '10kW Inverter',
            estimatedPrice: 75000.0,
            isAutoGenerated: true,
            category: 'inverter',
          ),
          const ProjectRowModel(
            id: '3',
            title: 'Installation & Mounting',
            quantity: 1,
            unit: 'lot',
            description: 'Installation & Mounting',
            estimatedPrice: 40000.0,
            isAutoGenerated: true,
            category: 'installation',
          ),
        ],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        isDefault: true,
      ),
    ];
  }
}
