import 'dart:io';
import 'package:share_plus/share_plus.dart';

/// Service class for sharing files and content
/// Handles sharing PDFs, images, and text via native sharing dialog
class ShareService {
  /// Share a PDF file
  /// Returns true if the sharing dialog was opened successfully
  static Future<bool> sharePdf(File pdfFile, String subject) async {
    try {
      // Validate file exists
      if (!await pdfFile.exists()) {
        throw Exception('PDF file does not exist');
      }

      await Share.shareXFiles(
        [XFile(pdfFile.path)],
        subject: subject,
        text: 'Please find attached your solar quotation.',
      );

      // The share dialog was opened successfully
      // Note: We can't determine if the user actually shared or just dismissed
      // So we return true to indicate the dialog opened without errors
      return true;
    } catch (e) {
      throw Exception('Failed to share PDF: $e');
    }
  }

  /// Share a PNG image
  static Future<void> shareImage(File imageFile, String subject) async {
    try {
      await Share.shareXFiles(
        [XFile(imageFile.path)],
        subject: subject,
        text: 'Your solar quotation summary.',
      );
    } catch (e) {
      throw Exception('Failed to share image: $e');
    }
  }

  /// Share text content
  static Future<void> shareText(String text, String subject) async {
    try {
      await Share.share(text, subject: subject);
    } catch (e) {
      throw Exception('Failed to share text: $e');
    }
  }

  /// Share quote summary as text
  static Future<void> shareQuoteSummary({
    required String projectName,
    required String clientName,
    required double systemSize,
    required double totalPrice,
    required bool isOffGrid,
    double? batterySize,
  }) async {
    final summary = '''
Solar Quotation Summary

Project: $projectName
Client: $clientName
System Size: ${systemSize.toStringAsFixed(2)} kW
${isOffGrid ? 'Battery Size: ${batterySize?.toStringAsFixed(2)} kWh\n' : ''}
Total Amount: ₱${totalPrice.toStringAsFixed(2)}

Generated by Solarize App
    ''';

    await shareText(summary, 'Solar Quotation - $projectName');
  }
}
