/// Model representing a project row/item in a quote
class ProjectRowModel {
  final String id;
  final int quantity;
  final String unit;
  final String description;
  final double estimatedPrice;
  final bool isAutoGenerated;
  final String? category;

  const ProjectRowModel({
    required this.id,
    required this.quantity,
    required this.unit,
    required this.description,
    required this.estimatedPrice,
    this.isAutoGenerated = false,
    this.category,
  });

  /// Calculate total price for this row
  double get totalPrice => quantity * estimatedPrice;

  /// Create a copy with updated values
  ProjectRowModel copyWith({
    String? id,
    int? quantity,
    String? unit,
    String? description,
    double? estimatedPrice,
    bool? isAutoGenerated,
    String? category,
  }) {
    return ProjectRowModel(
      id: id ?? this.id,
      quantity: quantity ?? this.quantity,
      unit: unit ?? this.unit,
      description: description ?? this.description,
      estimatedPrice: estimatedPrice ?? this.estimatedPrice,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      category: category ?? this.category,
    );
  }

  /// Convert to JSON
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'quantity': quantity,
      'unit': unit,
      'description': description,
      'estimatedPrice': estimatedPrice,
      'isAutoGenerated': isAutoGenerated,
      'category': category,
    };
  }

  /// Create from JSON
  factory ProjectRowModel.fromJson(Map<String, dynamic> json) {
    return ProjectRowModel(
      id: json['id'] as String,
      quantity: json['quantity'] as int,
      unit: json['unit'] as String,
      description: json['description'] as String,
      estimatedPrice: (json['estimatedPrice'] as num).toDouble(),
      isAutoGenerated: json['isAutoGenerated'] as bool? ?? false,
      category: json['category'] as String?,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is ProjectRowModel &&
        other.id == id &&
        other.quantity == quantity &&
        other.unit == unit &&
        other.description == description &&
        other.estimatedPrice == estimatedPrice &&
        other.isAutoGenerated == isAutoGenerated &&
        other.category == category;
  }

  @override
  int get hashCode {
    return Object.hash(
      id,
      quantity,
      unit,
      description,
      estimatedPrice,
      isAutoGenerated,
      category,
    );
  }

  @override
  String toString() {
    return 'ProjectRowModel(id: $id, quantity: $quantity, unit: $unit, description: $description, estimatedPrice: $estimatedPrice, isAutoGenerated: $isAutoGenerated, category: $category)';
  }
}
