/// Model class representing a single row/item in a quotation
/// Used for both quotes and presets
class ProjectRowModel {
  final String id;
  final int quantity;
  final String unit;
  final String description;
  final double estimatedPrice;
  final bool isAutoGenerated; // True for solar panels and battery rows
  final String?
  category; // e.g., 'solar_panels', 'battery', 'installation', etc.

  const ProjectRowModel({
    required this.id,
    required this.quantity,
    required this.unit,
    required this.description,
    required this.estimatedPrice,
    this.isAutoGenerated = false,
    this.category,
  });

  /// Create a copy of the row with updated values
  ProjectRowModel copyWith({
    String? id,
    int? quantity,
    String? unit,
    String? description,
    double? estimatedPrice,
    bool? isAutoGenerated,
    String? category,
  }) {
    return ProjectRowModel(
      id: id ?? this.id,
      quantity: quantity ?? this.quantity,
      unit: unit ?? this.unit,
      description: description ?? this.description,
      estimatedPrice: estimatedPrice ?? this.estimatedPrice,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      category: category ?? this.category,
    );
  }

  /// Calculate total price for this row
  double get totalPrice => quantity * estimatedPrice;

  /// Convert row to JSON for storage
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'quantity': quantity,
      'unit': unit,
      'description': description,
      'estimatedPrice': estimatedPrice,
      'isAutoGenerated': isAutoGenerated,
      'category': category,
    };
  }

  /// Create row from JSON
  factory ProjectRowModel.fromJson(Map<String, dynamic> json) {
    return ProjectRowModel(
      id: json['id'] as String,
      quantity: json['quantity'] as int,
      unit: json['unit'] as String,
      description: json['description'] as String,
      estimatedPrice: (json['estimatedPrice'] as num).toDouble(),
      isAutoGenerated: json['isAutoGenerated'] as bool? ?? false,
      category: json['category'] as String?,
    );
  }

  @override
  String toString() {
    return 'ProjectRowModel(id: $id, description: $description, quantity: $quantity, price: $estimatedPrice)';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is ProjectRowModel && other.id == id;
  }

  @override
  int get hashCode => id.hashCode;
}
